version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./packages/docker-config/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MYMECUM_ID=${MYMECUM_ID}
      - MYMECUM_SECRET=${MYMECUM_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=${NEXT_PUBLIC_ALGOLIA_APPLICATION_ID}
      - NEXT_PUBLIC_ALGOLIA_INDEX_NAME=${NEXT_PUBLIC_ALGOLIA_INDEX_NAME}
      - NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_KEY=${NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_KEY}
      - NEXT_PUBLIC_CLOUDINARY_DOMAIN=${NEXT_PUBLIC_CLOUDINARY_DOMAIN}
      - NEXT_PUBLIC_ENABLE_STELLATE=${NEXT_PUBLIC_ENABLE_STELLATE}
      - NEXT_PUBLIC_IMAGE_DOMAINS=${NEXT_PUBLIC_IMAGE_DOMAINS}
      - NEXT_PUBLIC_MYMECUM_DOMAIN=${NEXT_PUBLIC_MYMECUM_DOMAIN}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - ODR_SECRET=${ODR_SECRET}
      - UPSTASH_REDIS_ALLOWED_COUNTRIES=${UPSTASH_REDIS_ALLOWED_COUNTRIES}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - WORDPRESS_APPLICATION_PASSWORD=${WORDPRESS_APPLICATION_PASSWORD}
      - WORDPRESS_APPLICATION_USERNAME=${WORDPRESS_APPLICATION_USERNAME}
      - WORDPRESS_PREVIEW_SECRET=${WORDPRESS_PREVIEW_SECRET}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - NEXT_PUBLIC_SECRET=${NEXT_PUBLIC_SECRET}
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./packages/docker-config/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
